
language: c
# dist: bionic
os:
  - osx
  - linux
jobs:
  include:
    - os: osx
    - os: linux
      dist: bionic
addons:
  apt:
    packages: build-essential git rsync
  homebrew:
    packages: git rsync
# S: Build Lifecycle
install:
  - cp -r ./ ~/.dotfiles

# before_script:
#   - rm -rf folder 2> /dev/null

script:
  - yes | . ~/.dotfiles/bootstrap.sh

branches:
  only:
    - develop
env:
  global:
    - GH_REF: github.com/JMwill/dotfiles.git
